import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated sidebar file is produced by `docusaurus fetch-lark-docs`.
// Run `docusaurus fetch-lark-docs --manual guides --pubTarget zilliz.saas -s3` to regenerate.
// To customise without regenerating, edit config/sidebar-overrides/guides.json.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function tryRequire(path: string): any[] {
  try { return require(path) } catch { return [] }
}
// eslint-disable-next-line @typescript-eslint/no-var-requires
const applyOverrides = require('./config/applyOverrides')

const sidebars: SidebarsConfig = {
  // Cloud / BYOC guides — generated from Feishu wiki
  default: applyOverrides(
    tryRequire('./config/generated/guides.sidebar'),
    require.resolve('./config/sidebar-overrides/guides.json'),
  ),
  // Standalone sidebar for the Releases tab — auto-built from release notes directory
  releasesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tutorials/get-started/release-notes',
    },
  ],
};

export default sidebars;
