import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated sidebar file is produced by `docusaurus fetch-lark-docs`.
// Run `docusaurus fetch-lark-docs --manual guides --pubTarget zilliz.saas -s3` to regenerate.
// To customise without regenerating, edit config/sidebar-overrides/guides.json.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function tryRequire(path: string): any[] {
  try { return require(path) } catch { return [] }
}
function generatedOrFallback(path: string, fallback: any[]): any[] {
  const generated = tryRequire(path)
  return generated.length ? generated : fallback
}
// eslint-disable-next-line @typescript-eslint/no-var-requires
const applyOverrides = require('./config/applyOverrides')

const sidebars: SidebarsConfig = {
  // Cloud / BYOC guides — generated from Feishu wiki
  default: applyOverrides(
    tryRequire('./config/generated/guides.sidebar'),
    require.resolve('./config/sidebar-overrides/guides.json'),
  ),
  // Agents pages are stored in the Tools chapter but keep the legacy
  // /docs/agents/* route and displayed_sidebar from the previous site.
  agentsSidebar: generatedOrFallback('./config/generated/agents.sidebar', [
    {
      type: 'autogenerated',
      dirName: 'tutorials/tools/agents-and-prompts',
    },
  ]),
  // Standalone sidebar for the Releases tab — auto-built from release notes directory
  releasesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tutorials/release-notes',
    },
  ],
};

export default sidebars;
