/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorials'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'html',
      value: '<span class="sidebar__title">GET STARTED</span>',
      defaultStyle: true
    },
    'tutorials/get-started/register-with-zilliz-cloud',
    'tutorials/get-started/quick-start',
    {
      type: 'category',
      label: 'Concepts',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials/understand-basics'
        }
      ]
    },
    {
      type: 'category',
      label: 'API & SDKs',
      items: [
        {
          type: 'link',
          label: 'RESTful API',
          href: '/reference/restful'
        },
        {
          type: 'link',
          label: 'Python SDK',
          href: '/reference/python'
        },
        {
          type: 'link',
          label: 'Java SDK',
          href: '/reference/java'
        },
        {
          type: 'link',
          label: 'Node.js SDK',
          href: '/reference/nodejs'
        },
        {
          type: 'link',
          label: 'Go SDK',
          href: '/reference/go'
        }
      ]
    },
    'tutorials/get-started/example-dataset',
    'tutorials/get-started/free-trials',
    {
      type: 'category',
      label: 'Best Practices',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials/best-practices'
        }
      ]
    },
    {
      type: 'category',
      label: 'Release Notes',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials/release-notes'
        }
      ]      
    },    
    {
      type: 'html',
      value: '<span class="sidebar__title">CLUSTER</span>',
      defaultStyle: true
    },
    'tutorials/cluster/create-cluster',
    'tutorials/cluster/connect-to-cluster',
    'tutorials/cluster/manage-cluster',
    'tutorials/cluster/scale-cluster',
    'tutorials/cluster/manage-replica',
    'tutorials/cluster/database',
    {
      type: 'html',
      value: '<span class="sidebar__title">DATA GUIDES</span>',
      defaultStyle: true
    },
    {
      type: 'category',
      label: 'Collection',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials/collection'
        }
      ]
    },
    {
      type: 'category',
      label: 'Schema & Data Fields',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials/schema-data-fields'
        }
      ]
    },
    {
      type: 'category',
      label: 'Insert & Delete',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials/insert-update-delete'
        }
      ]
    },
    {
      type: 'category',
      label: 'Indexes',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials/manage-indexes'
        }
      ]
    },
    {
      type: 'category',
      label: 'Search & Rerank',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials/search-query-get'
        }
      ]
    },
    {
      type: 'category',
      label: 'Import & Export',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials/data-import-export'
        }
      ]
    },
    {
      type: 'html',
      value: '<span class="sidebar__title">MIGRATION</span>',
      defaultStyle: true
    },
    {
      type: 'category',
      label: 'Migrate from Milvus',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials/migrations/migrate-from-milvus'
        }
      ]
    }, 
    'tutorials/migrations/migrate-between-clusters',
    'tutorials/migrations/migrate-from-elasticsearch',
    'tutorials/migrations/migrate-from-pgvector',
    'tutorials/migrations/migrate-from-pinecone',
    'tutorials/migrations/migrate-from-qdrant',
    'tutorials/migrations/migrate-from-tencent-cloud',
    {
      type: 'html',
      value: '<span class="sidebar__title">MONITOR & ALERT</span>',
      defaultStyle: true
    }, 
    'tutorials/metrics-and-alerts/manage-organization-alerts',
    'tutorials/metrics-and-alerts/manage-project-alerts',
    'tutorials/metrics-and-alerts/manage-notification-channels',
    'tutorials/metrics-and-alerts/view-cluster-metric-charts',
    'tutorials/metrics-and-alerts/metrics-alerts-reference',
    'tutorials/metrics-and-alerts/prometheus-monitoring',
    {
      type: 'html',
      value: '<span class="sidebar__title">BACKUP & RESTORE</span>',
      defaultStyle: true
    },  
    'tutorials/backup-and-restore/create-snapshot',
    'tutorials/backup-and-restore/schedule-automatic-backups',
    'tutorials/backup-and-restore/view-snapshot-details',
    'tutorials/backup-and-restore/restore-from-snapshot',
    'tutorials/backup-and-restore/delete-snapshot', 
    {
      type: 'html',
      value: '<span class="sidebar__title">ORGANIZATIONS</span>',
      defaultStyle: true
    }, 
    'tutorials/organizations/organization-settings',
    'tutorials/organizations/organization-users',
    'tutorials/organizations/view-activities',
    'tutorials/organizations/use-recycle-bin',
    {
      type: 'html',
      value: '<span class="sidebar__title">PROJECTS</span>',
      defaultStyle: true
    },
    'tutorials/projects/manage-projects',
    'tutorials/projects/project-users',
    'tutorials/projects/job-center',
    {
      type: 'html',
      value: '<span class="sidebar__title">PIPELINES</span>',
      defaultStyle: true
    },
    {
      type: 'doc',
      label: 'Pipelines Quickstart',
      id: 'tutorials/pipelines/building-a-rag-app-with-pipelines'
    },
    {
      type: 'category',
      label: 'Ingest, Search, Delete',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials/pipelines/pipelines-ingest-search-delete-data'
        }
      ]
    },
    'tutorials/pipelines/connectors',
    {
      type: 'category',
      label: 'Pipelines Concepts',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials/pipelines/pipelines-concepts'
        }
      ]
    },
    {
      type: 'category',
      label: 'Pipelines Integrations',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials/pipelines/pipeline-integrations'
        }
      ]
    },
    {
      type: 'category',
      label: 'Pipelines Pricing',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials/pipelines/pipelines-pricing'
        }
      ]
    },
    {
      type: 'html',
      value: '<span class="sidebar__title">SECURITY</span>',
      defaultStyle: true
    },  
    {
      type: 'category',
      label: 'Authentication',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials/authentication'
        }
      ]
    },
    {
      type: 'category',
      label: 'Access Control',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials/access-control'
        }
      ]
    },
    {
      type: 'category',
      label: 'Private Endpoints',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials/network-and-security/setup-a-private-link'
        }
      ]
    },
    'tutorials/network-and-security/setup-whitelist',
    {
      type: 'html',
      value: '<span class="sidebar__title">PAYMENT & BILLING</span>',
      defaultStyle: true
    },  
    'tutorials/payment-billing/understand-cost',
    'tutorials/payment-billing/subscribe-by-adding-credit-card',
    'tutorials/payment-billing/subscribe-on-aws-marketplace',
    'tutorials/payment-billing/subscribe-on-gcp-marketplace',
    'tutorials/payment-billing/subscribe-on-azure-marketplace',
    'tutorials/payment-billing/advance-pay',
    'tutorials/payment-billing/view-invoice',
    {
      type: 'html',
      value: '<span class="sidebar__title">LIMIT & RESTRICTIONS</span>',
      defaultStyle: true
    }, 
    'tutorials/limits-and-restrictions/limits',
    'tutorials/limits-and-restrictions/api-comparison',
    {
      type: 'html',
      value: '<span class="sidebar__title">FAQS</span>',
      defaultStyle: true
    }, 
    {
      type: 'category',
      label: 'FAQs',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials/faqs'
        }
      ]
    } 
  ]
};

module.exports = sidebars;
