#!/bin/sh
set -eu

cat > /etc/nginx/chat-agent-runtime.conf <<EOF
resolver 10.255.0.10 valid=30s ipv6=off;

upstream docs_agent {
  zone docs_agent 64k;
  hash \$http_x_conversation_id consistent;
  server cloud-ai-assistant-0.cloud-ai-assistant-hs.vdc.svc.cluster.local:9000 resolve;
  server cloud-ai-assistant-1.cloud-ai-assistant-hs.vdc.svc.cluster.local:9000 resolve;
  server cloud-ai-assistant-2.cloud-ai-assistant-hs.vdc.svc.cluster.local:9000 resolve;
}
EOF

env_js="${INSTALL_PATH:-/usr/share/nginx/html}/env.js"

escape_js() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

release_channel="${ZDOC_RELEASE_CHANNEL:-current}"

cat > "$env_js" <<EOF
window.__ZDOC_ENV__ = {
  INKEEP_API_KEY: "$(escape_js "${INKEEP_API_KEY:-}")",
  INKEEP_INTEGRATION_ID: "$(escape_js "${INKEEP_INTEGRATION_ID:-}")",
  INKEEP_ORGANIZATION_ID: "$(escape_js "${INKEEP_ORGANIZATION_ID:-}")",
  RELEASE_CHANNEL: "$(escape_js "$release_channel")"
};
EOF

# Server-side gate, per channel direction:
# - on CURRENT deployments, block NEXT-channel routes that the build listed in
#   release-channel-routes.txt (unreleased pages);
# - on NEXT deployments, block RETIRE-IN-NEXT routes listed in
#   release-channel-retired-routes.txt (pages staged for removal by the
#   upcoming release, so the next channel previews the post-split world).
# The localized build passes append their own listing (for example the English
# image's ja-JP pass), so both files are merged per listing. Deployments serve
# the opposite direction's routes untouched; a missing routes file gates
# nothing.
# The generated locations must land in server context: conf.d/*.conf is
# included at http level by the base image, where `location` is invalid. The
# site nginx.conf files include this directory inside their server block; an
# empty directory matches nothing and nginx starts unchanged.
gate_dir="/etc/nginx/release-channel-gate"
mkdir -p "$gate_dir"
install_path="${INSTALL_PATH:-/usr/share/nginx/html}"
collect_release_channel_routes() {
  cat "$install_path/release-channel-routes.txt" "$install_path"/*/release-channel-routes.txt 2>/dev/null || true
}
collect_release_channel_retired_routes() {
  cat "$install_path/release-channel-retired-routes.txt" "$install_path"/*/release-channel-retired-routes.txt 2>/dev/null || true
}
write_release_channel_gate() {
  gate_conf="$1"
  gate_label="$2"
  gate_routes="$3"
  {
    echo "# Generated by 40-zdoc-env.sh — $gate_label are blocked on this deployment."
    printf '%s\n' "$gate_routes" | while IFS= read -r route; do
      case "$route" in
        /*) ;;
        *) continue ;;
      esac
      # Conservative route charset: ASCII path characters plus % for
      # URL-encoded bytes; anything else is dropped rather than trusted.
      case "$route" in
        *[!A-Za-z0-9._/~%-]*) continue ;;
      esac
      printf 'location = %s { error_page 404 /404.html; return 404; }\n' "$route"
      printf 'location = %s/ { error_page 404 /404.html; return 404; }\n' "$route"
    done
  } > "$gate_conf"
}
if [ "$release_channel" != "next" ] && [ -n "$(collect_release_channel_routes)" ]; then
  write_release_channel_gate "$gate_dir/blocked-routes.conf" "NEXT-channel routes" \
    "$(collect_release_channel_routes)"
  echo "Release channel '$release_channel': blocked NEXT routes in $gate_dir/blocked-routes.conf"
else
  rm -f "$gate_dir/blocked-routes.conf"
fi
if [ "$release_channel" = "next" ] && [ -n "$(collect_release_channel_retired_routes)" ]; then
  write_release_channel_gate "$gate_dir/blocked-retired-routes.conf" "RETIRE-IN-NEXT routes" \
    "$(collect_release_channel_retired_routes)"
  echo "Release channel '$release_channel': blocked retired routes in $gate_dir/blocked-retired-routes.conf"
else
  rm -f "$gate_dir/blocked-retired-routes.conf"
fi
