// Generated by scripts/generate-reference-presentation.js — do not edit.
export const referenceTargetKinds = ["python", "java", "nodejs", "go", "cpp", "cli", "restful"] as const;
export type ReferenceTargetKind = (typeof referenceTargetKinds)[number];

export const referenceTargetAliases: Readonly<Record<string, ReferenceTargetKind>> = {
  "python": "python",
  "java": "java",
  "nodejs": "nodejs",
  "node": "nodejs",
  "go": "go",
  "cpp": "cpp",
  "cli": "cli",
  "restful": "restful",
};

export const referenceTargetNavigation: ReadonlyArray<Readonly<{kind: ReferenceTargetKind; label: {en: string; 'zh-CN': string}; landingHref: string; hrefPrefixes: readonly string[]}>> = [
  {kind: "python", label: {en: "Python SDK", 'zh-CN': "Python SDK"}, landingHref: "/reference/python", hrefPrefixes: ["/reference/python"]},
  {kind: "java", label: {en: "Java SDK", 'zh-CN': "Java SDK"}, landingHref: "/reference/java", hrefPrefixes: ["/reference/java"]},
  {kind: "nodejs", label: {en: "Node.js SDK", 'zh-CN': "Node.js SDK"}, landingHref: "/reference/nodejs", hrefPrefixes: ["/reference/nodejs", "/reference/node"]},
  {kind: "go", label: {en: "Go SDK", 'zh-CN': "Go SDK"}, landingHref: "/reference/go", hrefPrefixes: ["/reference/go"]},
  {kind: "cpp", label: {en: "C++ SDK", 'zh-CN': "C++ SDK"}, landingHref: "/reference/cpp", hrefPrefixes: ["/reference/cpp"]},
  {kind: "cli", label: {en: "CLI", 'zh-CN': "Zilliz CLI"}, landingHref: "/reference/cli", hrefPrefixes: ["/reference/cli"]},
  {kind: "restful", label: {en: "REST API", 'zh-CN': "RESTful API"}, landingHref: "/reference/restful", hrefPrefixes: ["/reference/restful"]},
];
