// Generated by scripts/generate-reference-presentation.js — do not edit.
export const referenceTargetKinds = ["python", "java", "nodejs", "go", "restful", "cli"] as const;
export type ReferenceTargetKind = (typeof referenceTargetKinds)[number];

export const referenceTargetAliases: Readonly<Record<string, ReferenceTargetKind>> = {
  "python": "python",
  "java": "java",
  "nodejs": "nodejs",
  "node": "nodejs",
  "go": "go",
  "restful": "restful",
  "cli": "cli",
};

export const referenceTargetNavigation: ReadonlyArray<Readonly<{kind: ReferenceTargetKind; landingHref: string; hrefPrefixes: readonly string[]}>> = [
  {kind: "python", landingHref: "/reference/python", hrefPrefixes: ["/reference/python"]},
  {kind: "java", landingHref: "/reference/java", hrefPrefixes: ["/reference/java"]},
  {kind: "nodejs", landingHref: "/reference/nodejs", hrefPrefixes: ["/reference/nodejs", "/reference/node"]},
  {kind: "go", landingHref: "/reference/go", hrefPrefixes: ["/reference/go"]},
  {kind: "restful", landingHref: "/reference/restful", hrefPrefixes: ["/reference/restful"]},
  {kind: "cli", landingHref: "/reference/cli", hrefPrefixes: ["/reference/cli"]},
];
