import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
export default {default: [{type: 'autogenerated', dirName: 'agents-and-prompts'}], agentsSidebar: [{type: 'autogenerated', dirName: 'agents-and-prompts'}]} satisfies SidebarsConfig;
