import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
export default {default: [{type: 'autogenerated', dirName: 'tutorials'}], tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorials'}]} satisfies SidebarsConfig;
