import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
export default {default: [{type: 'autogenerated', dirName: 'docs'}], onPremiseSidebar: [{type: 'autogenerated', dirName: 'docs'}]} satisfies SidebarsConfig;
