import {readFileSync} from 'node:fs';
import path from 'node:path';

import {describe, expect, it} from 'vitest';

import sidebars from './reference';
import {loadPublishedSidebar} from './referenceLoader';

const names = [
  'pythonSidebar',
  'javaSidebar',
  'nodeSidebar',
  'goSidebar',
  'cppSidebar',
  'cliSidebar',
  'restfulSidebar',
] as const;

// References with a published zh-CN translation must be non-empty. cpp is
// excluded: its translation is optional and may not have landed yet, so its
// generated sidebar can legitimately be empty (tolerated by loadPublishedSidebar).
const translatedNames = names.filter(name => name !== 'cppSidebar');

type SidebarNode = Readonly<{
  label?: string;
  type?: string;
  items?: readonly SidebarNode[];
}>;

function collectCategoryLabels(items: readonly SidebarNode[]): string[] {
  return items.flatMap(item => [
    ...(item.type === 'category' && item.label ? [item.label] : []),
    ...(item.items ? collectCategoryLabels(item.items) : []),
  ]);
}

describe('zh-CN reference sidebars', () => {
  it('loads seven isolated published sidebars', () => {
    expect(Object.keys(sidebars)).toEqual(names);
    for (const name of names) {
      expect(Array.isArray(sidebars[name])).toBe(true);
    }
    for (const name of translatedNames) {
      expect(sidebars[name].length).toBeGreaterThan(0);
    }
  });

  it('tolerates an empty generated sidebar for an untranslated reference', () => {
    const empty = loadPublishedSidebar('cpp', () => [], '/unused.json');
    expect(Array.isArray(empty)).toBe(true);
    expect(empty.length).toBe(0);
  });

  it('fails closed for a missing or non-array generated artifact', () => {
    expect(() => loadPublishedSidebar('python', () => {
      throw new Error('missing module');
    }, '/unused.json')).toThrow(/python.*generated sidebar.*missing module/i);
    expect(() => loadPublishedSidebar('python', () => ({default: {}}), '/unused.json'))
      .toThrow(/python.*non-empty array/i);
  });

  it('contains no autogenerated all-docs fallback', () => {
    const source = readFileSync(
      path.resolve(process.cwd(), 'packages/site-config/src/sidebars/zh-CN/reference.ts'),
      'utf8',
    );
    expect(source).not.toContain("type: 'autogenerated'");
  });

  it('presents RESTful operations without V1 and V2 wrapper categories', () => {
    const labels = collectCategoryLabels(sidebars.restfulSidebar as SidebarNode[]);
    expect(labels).not.toContain('V1');
    expect(labels).not.toContain('V2');
  });
});
