import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
const all = [{type: 'autogenerated' as const, dirName: '.'}];
export default {default: all, pythonSidebar: all, javaSidebar: all, nodeSidebar: all, goSidebar: all, cliSidebar: all, restfulSidebar: all} satisfies SidebarsConfig;
